kind: Workflow
apiVersion: v1
name: Test2 Email Workflow
domain: test2.emailWorkflow
key: test-webhook-ai-workflow-key
description: A test workflow for ai processing
version: 1
active: true
nodes:

  start:
    type: START
    actor: SYSTEM
    component: dev.fusionize.web.FileInboundConnector
    config:
      storage: test-s3-storage
      output: myFile
    next: [process]

  process:
    type: TASK
    actor: AI
    component: dev.fusionize.ai.DocumentExtractor
    config:
      storage: test-s3-storage
      input: myFile
      output: out
      example:
        userName: string
        location: string
        age: int
    next: [ end ]

  end:
    type: END
    actor: SYSTEM
    component: dev.fusionize.orchestrator.components.MyCustomComponentEnd
    next: []
